name: Deploy server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run cleanup script
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
          ssh -i /home/runner/.ssh/github_actions -o StrictHostKeyChecking=no ubuntu@${{secrets.HOST}} 'bash -s' < .github/cleanup.sh
      - name: Dokku deploy
        uses: titi-lima/dokku-github-action@v1
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          PROJECT: server
          BRANCH: main
          FORCE_DEPLOY: true
