name: ESLint action, typecheck and build

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Installs all the packages
      - name: Install dependencies and packages
        run: yarn install

        # Generate prisma client
      - name: Generate prisma client
        run: yarn generate:ci

      # Runs the lint script
      - name: Run the lint Script
        run: yarn lint

      # Runs the typecheck script
      - name: Run the typecheck Script
        run: yarn typecheck

      # Runs the build script
      - name: Run the build Script
        run: yarn build
